'use strict';
const {db,esc,list,save,safeURL}=SM,$=s=>document.querySelector(s);
const ADMIN_EMAILS={badr:'t23782275@gmail.com',mohamed:'vhvhbhvh7@gmail.com',alaa:'ncjvunfbycjvg@gmail.com'};
const specs={
 sm_products:{title:'الألعاب وقطع الغيار',fields:[['name_ar','اسم المنتج'],['category','القسم','select','games:ألعاب|parts:قطع الغيار|safety:السلامة والحماية'],['price','السعر بالريال','number'],['unit_ar','وحدة البيع'],['image','رابط صورة المنتج','text'],['aliases','كلمات البحث المشابهة'],['description_ar','الوصف','textarea'],['featured','منتج مميز','checkbox'],['published','منشور','checkbox']]},
 sm_centers:{title:'المراكز وأعمالنا',fields:[['name_ar','اسم المركز'],['city_ar','المدينة'],['logo','رابط شعار المركز'],['gallery','صور المعرض: رابط في كل سطر والترتيب من الأعلى للأسفل','textarea'],['image','رابط الصورة','text'],['published','منشور','checkbox']]},
 sm_pages:{title:'الصفحات والبنرات',fields:[['title_ar','العنوان'],['body_ar','المحتوى','textarea'],['image','رابط صورة أو بنر','text'],['published','منشور','checkbox']]},
 sm_settings:{title:'إعدادات الموقع',fields:[['brand_ar','اسم المؤسسة'],['whatsapp','واتساب بصيغة دولية بدون +'],['instagram','رابط إنستغرام','url'],['phone','رقم الاتصال'],['logo','رابط شعار الموقع'],['facebook','فيسبوك','url'],['tiktok','تيك توك','url'],['youtube','يوتيوب','url'],['catalog','رابط الكتالوج','url'],['payment_ar','تعليمات الدفع','textarea'],['shipping_ar','تفاصيل الشحن','textarea']]},
 sm_orders:{title:'الطلبات',fields:[['status','حالة الطلب','select','pending:جديد|reviewing:قيد المراجعة|quoted:تم إرسال السعر|completed:مكتمل|cancelled:ملغي']]}
}
let table='sm_products',rows=[],editing=null,demo=false,busy=false;const demoData=structuredClone(SM_SEED);demoData.sm_orders=[];
function notify(t){$('#message').textContent=t;$('#message').style.display='block';setTimeout(()=>$('#message').style.display='none',5000)}
function start(){ $('#login').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;$('#mode').textContent='متصل بقاعدة البيانات — التعديلات المنشورة تظهر للعملاء عند تحديث الصفحة.';$('#tabs').innerHTML=Object.entries(specs).map(([k,v])=>`<button data-table="${k}">${v.title}</button>`).join('');load();}
async function load(){try{rows=demo?demoData[table]:await list(table);$('#heading').textContent=specs[table].title;$('#new').hidden=table==='sm_orders'||(table==='sm_settings'&&rows.length>0);document.querySelectorAll('[data-table]').forEach(b=>b.classList.toggle('active',b.dataset.table===table));render()}catch(e){notify('تعذر التحميل: '+e.message)}}
const orderStatusLabels={pending:'جديد',reviewing:'قيد المراجعة',quoted:'تم إرسال السعر',completed:'مكتمل',cancelled:'ملغي'};
const translationFields={
 sm_products:[['name_ar','name_en'],['unit_ar','unit_en'],['description_ar','description_en']],
 sm_centers:[['name_ar','name_en'],['city_ar','city_en']],
 sm_pages:[['title_ar','title_en'],['body_ar','body_en']],
 sm_settings:[['brand_ar','brand_en'],['payment_ar','payment_en'],['shipping_ar','shipping_en']]
};
async function translateRow(kind,row){
 const pairs=translationFields[kind]||[];if(!pairs.length)return row;
 if(demo||!db){for(const[a,b]of pairs)if(!row[b])row[b]=row[a]||'';return row;}
 const texts=pairs.map(([a])=>String(row[a]||''));
 const {data,error}=await db.functions.invoke('sm-admin-translate',{body:{texts}});
 if(error||!data||!Array.isArray(data.translations)||data.translations.length!==pairs.length)throw Error('تعذر إنشاء الترجمة الإنجليزية تلقائيًا. جرّب الحفظ مرة أخرى.');
 pairs.forEach(([a,b],i)=>row[b]=String(data.translations[i]||row[a]||'').trim());
 return row;
}
function selectOptions(raw,val){return String(raw||'').split('|').filter(Boolean).map(item=>{const i=item.indexOf(':'),value=i<0?item:item.slice(0,i),label=i<0?item:item.slice(i+1);return `<option value="${esc(value)}" ${String(val)===value?'selected':''}>${esc(label)}</option>`}).join('')}
function orderMoney(n){return new Intl.NumberFormat('ar-SA',{maximumFractionDigits:2}).format(Number(n)||0)+' ر.س'}
function orderDate(v){try{return new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return v||''}}
function orderField(label,value){if(value===undefined||value===null||String(value).trim()==='')return '';return `<div class="orderField"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`}
function orderItems(items){if(!Array.isArray(items)||!items.length)return '<p class="orderEmpty">لا توجد منتجات في الطلب.</p>';return `<div class="orderItems">${items.map((item,i)=>{const name=item.name_ar||item.name_en||`منتج ${i+1}`,qty=Number(item.quantity)||0,price=Number(item.unit_price)||0;return `<div class="orderItem"><div><strong>${esc(name)}</strong><small>الكمية: ${esc(qty)}</small></div><div class="orderItemPrice"><span>${orderMoney(price)} × ${esc(qty)}</span><b>${orderMoney(price*qty)}</b></div></div>`}).join('')}</div>`}
function orderCard(r){const c=r.contact&&typeof r.contact==='object'?r.contact:{},phone=c.recipient_phone||c.phone||r.phone||'',wa=SM.saPhone(phone),status=orderStatusLabels[r.status]||r.status||'',subtotal=r.estimated_subtotal||0;return `<article class="orderCard"><div class="orderTop"><div><span class="orderNumber">طلب #${esc(String(r.id||'').slice(0,8))}</span><h3>${esc(r.company||c.company||'طلب عميل')}</h3><small>${esc(orderDate(r.created_at))}</small></div><span class="statusBadge status-${esc(r.status||'pending')}">${esc(status)}</span></div><div class="orderSection"><h4>بيانات العميل</h4><div class="orderFields">${orderField('اسم المسؤول',r.contact_name||c.contact_name)}${orderField('رقم الجوال',r.phone||c.phone)}${orderField('البريد الإلكتروني',r.email||c.email)}${orderField('الرقم الضريبي',c.tax_number)}</div></div><div class="orderSection"><h4>عنوان الشحن</h4><div class="orderFields">${orderField('الدولة',c.country)}${orderField('المنطقة',c.region)}${orderField('المدينة',c.city)}${orderField('العنوان',c.address)}${orderField('جوال المستلم',c.recipient_phone)}</div></div>${c.notes?`<div class="orderSection"><h4>ملاحظات العميل</h4><p class="orderNotes">${esc(c.notes)}</p></div>`:''}<div class="orderSection"><h4>المنتجات</h4>${orderItems(r.items)}</div><div class="orderBottom"><div class="orderTotal"><span>الإجمالي التقديري</span><strong>${orderMoney(subtotal)}</strong></div><div class="orderActions">${wa?`<a class="whatsapp orderWhatsApp" href="https://wa.me/${wa}" target="_blank" rel="noopener">واتساب العميل</a>`:''}<button data-edit="${esc(r.id)}">تغيير حالة الطلب</button></div></div></article>`}
function render(){const q=$('#search').value;$('#stats').innerHTML=`<span>السجلات: ${rows.length}</span><span>القسم: ${specs[table].title}</span>`;const shown=rows.filter(r=>JSON.stringify(r).includes(q));if(table==='sm_orders'){$('#records').innerHTML=shown.length?shown.map(orderCard).join(''):'<article>لا توجد طلبات مطابقة.</article>';return;}$('#records').innerHTML=shown.length?shown.map(r=>`<article>${r.image?`<img src="${esc(safeURL(r.image))}" alt="">`:''}<div class="body"><h3>${esc(r.name_ar||r.title_ar||r.brand_ar||r.company||r.id)}</h3><p>${esc(r.city_ar||r.category||r.slug||r.status||'')}</p>${r.price!=null?`<p>${esc(r.price)} ر.س / ${esc(r.unit_ar)}</p>`:''}${r.published===false?'<small>مخفي عن العملاء</small>':''}</div><div class="actions"><button data-edit="${esc(r.id)}">تعديل</button>${['sm_products','sm_centers','sm_pages'].includes(table)?`<button class="danger" data-delete="${esc(r.id)}">حذف</button>`:''}</div></article>`).join(''):'<article>لا توجد سجلات مطابقة.</article>';}
function edit(id){editing=rows.find(r=>String(r.id)===id)||{};$('#formError').textContent='';$('#fields').innerHTML=`<div class="autoTranslateNote">اكتب بالعربي فقط — الترجمة الإنجليزية تُنشأ تلقائيًا عند الحفظ وتظهر للعميل عند اختيار English.</div>`+specs[table].fields.map(([key,label,type='text',options])=>{const val=(key==='gallery'?(editing.gallery||[]).join('\n'):editing[key])??(type==='checkbox'?true:'');let control;if(type==='textarea')control=`<textarea name="${key}" rows="4">${esc(val)}</textarea>`;else if(type==='select')control=`<select name="${key}">${selectOptions(options,val)}</select>`;else control=`<input name="${key}" type="${type}" ${type==='checkbox'?(val?'checked':''):`value="${esc(val)}"`} ${type==='number'?'min="0" step="0.01"':''} ${['name_ar','title_ar','brand_ar','price'].includes(key)?'required':''}>`;return `<label class="${type==='textarea'?'wide':''}">${label}${control}</label>`}).join('');if(['sm_products','sm_centers','sm_pages'].includes(table))$('#fields').insertAdjacentHTML('beforeend','<label class="wide">رفع صورة (PNG / JPEG / WebP، حتى 5 ميجابايت)<input type="file" id="upload" accept="image/png,image/jpeg,image/webp"><small>أو استخدم رابط صورة موجودة بالأعلى.</small></label>');if(table==='sm_centers')$('#fields').insertAdjacentHTML('beforeend','<label class="wide">رفع صور المعرض (تضاف بعد الصور الحالية)<input id="galleryUpload" type="file" multiple accept="image/png,image/jpeg,image/webp"></label><label>رفع شعار المركز<input id="logoUpload" type="file" accept="image/png,image/jpeg,image/webp"></label>');if(table==='sm_settings')$('#fields').insertAdjacentHTML('beforeend','<label>رفع شعار الموقع<input id="logoUpload" type="file" accept="image/png,image/jpeg,image/webp"></label>');$('#editor').showModal();}
$('#editForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const saveButton=$('#save'),oldSaveText=saveButton.textContent;saveButton.disabled=true;saveButton.textContent=table==='sm_orders'?'جاري الحفظ...':'جاري الترجمة والحفظ...';try{const row={...editing};for(const[k,,type]of specs[table].fields){const el=e.target.elements[k];row[k]=type==='checkbox'?el.checked:type==='number'?Number(el.value):el.value.trim();}if(table==='sm_centers'){row.gallery=row.gallery.split('\n').map(x=>x.trim()).filter(Boolean);if(row.gallery.some(x=>!safeURL(x)))throw Error('رابط صورة غير صالح');}if(!row.id)row.id=table==='sm_settings'?'global':crypto.randomUUID();if(table==='sm_pages'&&!row.slug)row.slug='page-'+Date.now();if(table!=='sm_orders')await translateRow(table,row);const file=$('#upload')?.files[0];if(file){if(file.size>5*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('صيغة الصورة أو حجمها غير مناسب');if(demo)throw Error('رفع الصور يحتاج ربط قاعدة البيانات. يمكنك تجربة رابط صورة في المعاينة.');else{const ext={'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[file.type],path=`${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('sm-media').upload(path,file,{contentType:file.type});if(error)throw error;row.image=db.storage.from('sm-media').getPublicUrl(path).data.publicUrl;}}if($('#logoUpload')?.files[0])row.logo=await uploadImage($('#logoUpload').files[0]);if(table==='sm_centers')for(const file of Array.from($('#galleryUpload')?.files||[]))row.gallery.push(await uploadImage(file));if(demo){const i=demoData[table].findIndex(r=>r.id===row.id);if(i<0)demoData[table].push(row);else demoData[table][i]=row;}else if(table==='sm_orders'){const{error}=await db.from(table).update({status:row.status}).eq('id',row.id);if(error)throw error;}else await save(table,row);$('#editor').close();await load();notify(demo?'تم تعديل المعاينة المحلية':'تم الحفظ والترجمة تلقائيًا')}catch(err){$('#formError').textContent=err.message}finally{busy=false;saveButton.disabled=false;saveButton.textContent=oldSaveText}};
$('#tabs').onclick=e=>{if(e.target.dataset.table){table=e.target.dataset.table;$('#search').value='';load()}};$('#new').onclick=()=>edit('');$('#close').onclick=()=>$('#editor').close();$('#refresh').onclick=load;$('#search').oninput=render;
$('#records').onclick=async e=>{if(e.target.dataset.edit)edit(e.target.dataset.edit);if(e.target.dataset.delete&&confirm('حذف هذا السجل؟ يمكنك إخفاؤه بدل الحذف من شاشة التعديل.')){try{const id=e.target.dataset.delete;if(demo)demoData[table]=demoData[table].filter(r=>r.id!==id);else{const{error}=await db.from(table).delete().eq('id',id);if(error)throw error}await load()}catch(err){notify(err.message)}}};
$('#logout').onclick=async()=>{if(db)await db.auth.signOut();location.reload()};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const errorBox=$('#loginError');errorBox.textContent='';if(!db){errorBox.textContent='تعذر الاتصال بقاعدة البيانات.';return}const button=e.target.querySelector('button');button.disabled=true;button.textContent='جاري الدخول...';try{const username=e.target.username.value.trim().toLowerCase(),password=e.target.password.value,email=ADMIN_EMAILS[username];if(!email||!password)throw Error('اسم المستخدم أو كلمة المرور غير صحيحة');const{data,error}=await db.auth.signInWithPassword({email,password});if(error||!data.user)throw Error('اسم المستخدم أو كلمة المرور غير صحيحة');const{data:adminRow,error:adminError}=await db.from('sm_admins').select('user_id').eq('user_id',data.user.id).maybeSingle();if(adminError||!adminRow){await db.auth.signOut();throw Error('هذا الحساب غير مصرح له بدخول الإدارة');}sessionStorage.setItem('sm-admin-username',username);e.target.password.value='';start()}catch(err){errorBox.textContent=err.message||'تعذر تسجيل الدخول';}finally{button.disabled=false;button.textContent='دخول'}};

async function uploadImage(file){if(!db)throw Error('رفع الصور يحتاج ربط قاعدة البيانات');if(file.size>5*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('كل صورة يجب أن تكون PNG/JPEG/WebP وأقل من 5 ميجابايت');const ext={'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[file.type],path=crypto.randomUUID()+'.'+ext;const {error}=await db.storage.from('sm-media').upload(path,file,{contentType:file.type});if(error)throw error;return db.storage.from('sm-media').getPublicUrl(path).data.publicUrl;}
async function restoreAdmin(){if(!db)return;const {data,error}=await db.auth.getUser();if(error||!data.user)return;const res=await db.from('sm_admins').select('user_id').eq('user_id',data.user.id).maybeSingle();if(res.data){history.replaceState(null,'',location.pathname);start()}else{await db.auth.signOut();notify('الحساب غير مصرح له بإدارة الموقع')}}restoreAdmin();
