'use strict';
const setupForm=document.querySelector('#setupForm'),recoveryForm=document.querySelector('#recoveryForm'),result=document.querySelector('#result');
const redirectTo=new URL('setup-account.html',location.href).href;
let busy=false;
async function run(action){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{if(!SM.db)throw Error('الربط غير متاح');await action();}catch(e){result.textContent=e.message;}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
setupForm.onsubmit=e=>{e.preventDefault();run(async()=>{if(setupForm.password.value!==setupForm.confirm.value)throw Error('كلمتا المرور غير متطابقتين');const {data,error}=await SM.db.auth.signUp({email:setupForm.email.value.trim(),password:setupForm.password.value,options:{emailRedirectTo:redirectTo}});setupForm.password.value='';setupForm.confirm.value='';if(error)throw error;if(data.session){await SM.db.auth.signOut();result.textContent='تم التسجيل. ارجع لدخول الإدارة باسم المستخدم؛ يلزم تأكيد البريد قبل تفعيل الصلاحية.';}else result.textContent='راجع بريدك لتأكيد الحساب، ثم ارجع لدخول الإدارة باسم المستخدم والباسورد. لو عندك حساب بالفعل استخدم استرجاع كلمة المرور.';});};
document.querySelector('#reset').onclick=()=>run(async()=>{if(!setupForm.email.checkValidity())throw Error('اكتب بريدك الإلكتروني الصحيح');const {error}=await SM.db.auth.resetPasswordForEmail(setupForm.email.value.trim(),{redirectTo});if(error)throw error;result.textContent='لو البريد مسجل، ستصلك تعليمات استرجاع كلمة المرور.';});
recoveryForm.onsubmit=e=>{e.preventDefault();run(async()=>{if(recoveryForm.password.value!==recoveryForm.confirm.value)throw Error('كلمتا المرور غير متطابقتين');const{error}=await SM.db.auth.updateUser({password:recoveryForm.password.value});if(error)throw error;recoveryForm.reset();await SM.db.auth.signOut();recoveryForm.hidden=true;setupForm.hidden=false;result.textContent='تم حفظ كلمة المرور. ارجع لدخول الإدارة.';});};
SM.db?.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'){setupForm.hidden=true;recoveryForm.hidden=false;history.replaceState(null,'',location.pathname);}});
